name: time_series
channels:
    - default
    - anaconda
dependencies:
    - python=3.6
    - pip
    - statsmodels
    - pandas
    - pip:
        - jupyter
        - pyramid-arima
        - matplotlib
        - tqdm
        - requests